name: Bug report
description: Report a bug with the integration
labels: ['Bug']
title: "[BUG] "
body:
- type: checkboxes
  id: latest-version
  attributes:
    label: Are you running the latest version?
    description: Pleasure ensure that you are running the latest version. Your issue might already have been dealt with.
    options:
      - label: I am running the latest version
        required: true
- type: input
  id: hvac-unit
  attributes:
    label: Device information
    description: "What HVAC unit do you have?"
  validations:
    required: true
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    description: "A clear and concise description of what the bug is. Attaching screenshots can be very helpful."
    render: bash
  validations:
    required: true
